config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills_and_interests
  resources :honors_and_awards
  resources :work_experiences
  devise_for :users
  root to: "dashboard#index"

  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  get 'dashboard/download'

  get 'work_experiences/index'

  get 'honors_and_awards/index'

  get 'skills_and_interests/index'

  get 'references/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  # GET /work_experiences
  # GET /work_experiences.json
  def index
    @work_experiences = WorkExperience.all
  end

  # GET /work_experiences/1
  # GET /work_experiences/1.json
  def show
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
  end

  # POST /work_experiences
  # POST /work_experiences.json
  def create
    @work_experience = WorkExperience.new(work_experience_params)

    respond_to do |format|
      if @work_experience.save
        format.html { redirect_to @work_experience, notice: 'Work experience was successfully created.' }
        format.json { render :show, status: :created, location: @work_experience }
      else
        format.html { render :new }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_experiences/1
  # PATCH/PUT /work_experiences/1.json
  def update
    respond_to do |format|
      if @work_experience.update(work_experience_params)
        format.html { redirect_to @work_experience, notice: 'Work experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_experience }
      else
        format.html { render :edit }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_experiences/1
  # DELETE /work_experiences/1.json
  def destroy
    @work_experience.destroy
    respond_to do |format|
      format.html { redirect_to work_experiences_url, notice: 'Work experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_experience_params
      params.require(:work_experience).permit(:owner, :start_date, :end_date, :name, :description)
    end
end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/work_experiences/_form.html.erb
<%= form_for(work_experience) do |f| %>
  <% if work_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_experience.errors.count, "error") %> prohibited this work_experience from being saved:</h2>

      <ul>
      <% work_experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :owner, :value => current_user.id %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, class: "form-control", placeholder: "Start date" %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, class: "form-control", placeholder: "End date" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/work_experiences/edit.html.erb
<h1>Editing Work Experience</h1>

<%= render 'form', work_experience: @work_experience %>

<%= link_to 'Show', @work_experience %> |
<%= link_to 'Back', dashboard_index_path %>

app/views/work_experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Experiences</h1>

<table class="table table-striped table-bordered table-hover" style="width:100%;">
  <thead>
    <tr>
      <!--<th>Owner</th>-->
      <th>Company Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Position</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody id = "experienceList" data-toggle="modal" data-target="#myModal">
    <% @work_experiences.each do |work_experience| %>
      <tr>
        <td><%= link_to work_experience.name, work_experience %></td>
        <td><%= work_experience.start_date %></td>
        <td><%= work_experience.end_date %></td>
        <td><%= work_experience.description %></td>
        <td><%= link_to 'Edit', edit_work_experience_path(work_experience) %>
          <span class="glyphicon glyphicon-edit"></span>
        </td>
        <td><%= link_to 'Destroy', work_experience, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' } %>
          <span class="glyphicon glyphicon-remove"></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Experience', new_work_experience_path, class: "btn btn-default" %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body" id="myModalBody">
      </div>
    </div>
  </div>
</div>

app/views/work_experiences/new.html.erb
<h1>New Work Experience</h1>

<%= render 'form', work_experience: @work_experience %>

<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @work_experience.owner %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @work_experience.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @work_experience.end_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @work_experience.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_experience.description %>
</p>

<%= link_to 'Edit', edit_work_experience_path(@work_experience) %> |
<%= link_to 'Back', dashboard_index_path %>