config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills_and_interests
  resources :honors_and_awards
  resources :work_experiences
  devise_for :users
  root to: "dashboard#index"

  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  get 'dashboard/download'

  get 'work_experiences/index'

  get 'honors_and_awards/index'

  get 'skills_and_interests/index'

  get 'references/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if user_signed_in?
      @references = Reference.where("owner = ?", current_user.id)
      @skills_and_interests = SkillsAndInterest.where("owner = ?", current_user.id)
      @work_experience = WorkExperience.where("owner = ?", current_user.id)
      @honors_and_awards = HonorsAndAward.where("owner = ?", current_user.id)
    end
  end

  def download
    user = User.find(current_user.id)
    @references = Reference.where("owner = ?", current_user.id)
    @skills_and_interests = SkillsAndInterest.where("owner = ?", current_user.id)
    @work_experience = WorkExperience.where("owner = ?", current_user.id)
    @honors_and_awards = HonorsAndAward.where("owner = ?", current_user.id)



        Caracal::Document.save '/public/Resume.docx' do |docx|
          docx.style do
            id 'Body'
            name 'body'
            font 'Segoe UI Light'
            size 24
          end
              
          # page 1
          docx.h1 do
            text user.first_name
            text ' '
            text user.last_name
          end

          docx.hr
          docx.p do
            text user.email
          end
          docx.hr

          docx.h2 'Work Experience'
          @work_experience.each do | experience |
            docx.p do
              style 'Body'
              text experience.name
              text ' ('
              text experience.start_date
              text ' - '
              text experience.end_date
              text ')'
              br
              text experience.description
            end
            docx.p
          end

          docx.p
          docx.h2 'Skills and Interests'
          @skills_and_interests.each do | skill |
            docx.p do
              style 'Body'
              text skill.skill_name
              br
              text skill.skill_description
            end
            docx.p
          end

          docx.p
          docx.h2 'Honors and Awards'
          @honors_and_awards.each do | honor |
            docx.p do
              style 'Body'
              text honor.honor_name
              text ' ('
              text honor.honor_date
              text ')'
              br
              text honor.honor_description
            end
            docx.p
          end

          docx.p
          docx.h2 'References'
          @references.each do | reference |
            docx.p do
              style 'Body'
              text reference.reference_name
              text ' '
              text reference.reference_contact_info
            end
            docx.p
          end









        end
        
        path = File.join(Rails.root, "public")
        send_file(File.join(path, "Resume.docx"))
  end

  def references
    @reference = Reference.where("owner = ?", current_user.id)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/DELETE/honors_and_awards.html.erb
<p id="notice"><%= notice %></p>

<h1>Honors And Awards</h1>
<p>Find me in app/views/dashboard/</p>

<%= @user.first_name %> <%= @user.last_name %>
<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Honor date</th>
      <th>Honor name</th>
      <th>Honor description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @honors_and_awards.each do |honors_and_award| %>
      <tr>
        <td><%= honors_and_award.owner %></td>
        <td><%= honors_and_award.honor_date %></td>
        <td><%= honors_and_award.honor_name %></td>
        <td><%= honors_and_award.honor_description %></td>
        <td><%= link_to 'Show', honors_and_award %></td>
        <td><%= link_to 'Edit', edit_honors_and_award_path(honors_and_award) %></td>
        <td><%= link_to 'Destroy', honors_and_award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honors And Award', new_honors_and_award_path %>

app/views/dashboard/DELETE/page1.html.erb
<h1>Dashboard#page1</h1>
<p>Find me in app/views/dashboard/page1.html.erb</p>

app/views/dashboard/DELETE/page2.html.erb
<h1>Dashboard#page2</h1>
<p>Find me in app/views/dashboard/page2.html.erb</p>

Hello, <%= @user.first_name %> <%= @user.last_name %>!

app/views/dashboard/DELETE/references.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>
<p>Find me in app/views/dashboard/</p>

<%= @user.first_name %> <%= @user.last_name %>
<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Reference name</th>
      <th>Reference contact info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.owner %></td>
        <td><%= reference.reference_name %></td>
        <td><%= reference.reference_contact_info %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

app/views/dashboard/DELETE/skills_and_interests.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills And Interests</h1>
<p>Find me in app/views/dashboard/</p>

<%= @user.first_name %> <%= @user.last_name %>
<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Skill name</th>
      <th>Skill description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills_and_interests.each do |skills_and_interest| %>
      <tr>
        <td><%= skills_and_interest.owner %></td>
        <td><%= skills_and_interest.skill_name %></td>
        <td><%= skills_and_interest.skill_description %></td>
        <td><%= link_to 'Show', skills_and_interest %></td>
        <td><%= link_to 'Edit', edit_skills_and_interest_path(skills_and_interest) %></td>
        <td><%= link_to 'Destroy', skills_and_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skills And Interest', new_skills_and_interest_path %>

app/views/dashboard/DELETE/work_experience.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Experiences</h1>
<p>Find me in app/views/dashboard/</p>

<%= @user.first_name %> <%= @user.last_name %>
<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_experiences.each do |work_experience| %>
      <tr>
        <td><%= work_experience.owner %></td>
        <td><%= work_experience.start_date %></td>
        <td><%= work_experience.end_date %></td>
        <td><%= work_experience.name %></td>
        <td><%= work_experience.description %></td>
        <td><%= link_to 'Show', work_experience %></td>
        <td><%= link_to 'Edit', edit_work_experience_path(work_experience) %></td>
        <td><%= link_to 'Destroy', work_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Experience', new_work_experience_path %>