config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills_and_interests
  resources :honors_and_awards
  resources :work_experiences
  devise_for :users
  root to: "dashboard#index"

  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  get 'dashboard/download'

  get 'work_experiences/index'

  get 'honors_and_awards/index'

  get 'skills_and_interests/index'

  get 'references/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:owner, :reference_name, :reference_contact_info)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(reference) do |f| %>
  <% if reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :owner, :value => current_user.id %>
  </div>

  <div class="field">
    <%= f.label :reference_name %>
    <%= f.text_field :reference_name %>
  </div>

  <div class="field">
    <%= f.label :reference_contact_info %>
    <%= f.text_field :reference_contact_info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', dashboard_index_path %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>

<table class="table table-striped table-bordered table-hover" style="width:100%;">
  <thead>
    <tr>
      <!--<th>Owner</th>-->
      <th>Reference name</th>
      <th>Reference contact info</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody id="refList" data-toggle="modal" data-target="#myModal">
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.reference_name %></td>
        <td><%= reference.reference_contact_info %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %>
          <span class="glyphicon glyphicon-edit"></span>
        </td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' } %>
          <span class="glyphicon glyphicon-remove"></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path, class: "btn btn-default" %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body" id="myModalBody">
      </div>
    </div>
  </div>
</div>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @reference.owner %>
</p>

<p>
  <strong>Reference name:</strong>
  <%= @reference.reference_name %>
</p>

<p>
  <strong>Reference contact info:</strong>
  <%= @reference.reference_contact_info %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', dashboard_index_path %>