config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills_and_interests
  resources :honors_and_awards
  resources :work_experiences
  devise_for :users
  root to: "dashboard#index"

  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  get 'dashboard/download'

  get 'work_experiences/index'

  get 'honors_and_awards/index'

  get 'skills_and_interests/index'

  get 'references/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/honors_and_award.rb
class HonorsAndAward < ApplicationRecord
end

app/controllers/honors_and_awards_controller.rb
class HonorsAndAwardsController < ApplicationController
  before_action :set_honors_and_award, only: [:show, :edit, :update, :destroy]

  # GET /honors_and_awards
  # GET /honors_and_awards.json
  def index
    @honors_and_awards = HonorsAndAward.all
  end

  # GET /honors_and_awards/1
  # GET /honors_and_awards/1.json
  def show
  end

  # GET /honors_and_awards/new
  def new
    @honors_and_award = HonorsAndAward.new
  end

  # GET /honors_and_awards/1/edit
  def edit
  end

  # POST /honors_and_awards
  # POST /honors_and_awards.json
  def create
    @honors_and_award = HonorsAndAward.new(honors_and_award_params)

    respond_to do |format|
      if @honors_and_award.save
        format.html { redirect_to @honors_and_award, notice: 'Honors and award was successfully created.' }
        format.json { render :show, status: :created, location: @honors_and_award }
      else
        format.html { render :new }
        format.json { render json: @honors_and_award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /honors_and_awards/1
  # PATCH/PUT /honors_and_awards/1.json
  def update
    respond_to do |format|
      if @honors_and_award.update(honors_and_award_params)
        format.html { redirect_to @honors_and_award, notice: 'Honors and award was successfully updated.' }
        format.json { render :show, status: :ok, location: @honors_and_award }
      else
        format.html { render :edit }
        format.json { render json: @honors_and_award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /honors_and_awards/1
  # DELETE /honors_and_awards/1.json
  def destroy
    @honors_and_award.destroy
    respond_to do |format|
      format.html { redirect_to honors_and_awards_url, notice: 'Honors and award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_honors_and_award
      @honors_and_award = HonorsAndAward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def honors_and_award_params
      params.require(:honors_and_award).permit(:owner, :honor_date, :honor_name, :honor_description)
    end
end

app/helpers/honors_and_awards_helper.rb
module HonorsAndAwardsHelper
end

app/views/honors_and_awards/_form.html.erb
<%= form_for(honors_and_award) do |f| %>
  <% if honors_and_award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(honors_and_award.errors.count, "error") %> prohibited this honors_and_award from being saved:</h2>

      <ul>
      <% honors_and_award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :owner, :value => current_user.id %>
  </div>

  <div class="field">
    <%= f.label :honor_date %>
    <%= f.text_field :honor_date %>
  </div>

  <div class="field">
    <%= f.label :honor_name %>
    <%= f.text_field :honor_name %>
  </div>

  <div class="field">
    <%= f.label :honor_description %>
    <%= f.text_field :honor_description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/honors_and_awards/edit.html.erb
<h1>Editing Honors And Award</h1>

<%= render 'form', honors_and_award: @honors_and_award %>

<%= link_to 'Show', @honors_and_award %> |
<%= link_to 'Back', dashboard_index_path %>

app/views/honors_and_awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Honors And Awards</h1>

<table class="table table-striped table-bordered table-hover" style="width:100%;">
  <thead>
    <tr>
      <!--<th>Owner</th>-->
      <th>Honor date</th>
      <th>Honor name</th>
      <th>Honor description</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody id="honorList" data-toggle="modal" data-target="#myModal">
    <% @honors_and_awards.each do |honors_and_award| %>
      <tr>
        <td><%= honors_and_award.honor_date %></td>
        <td><%= honors_and_award.honor_name %></td>
        <td><%= honors_and_award.honor_description %></td>
        <td><%= link_to 'Edit', edit_honors_and_award_path(honors_and_award) %>
          <span class="glyphicon glyphicon-edit"></span>
        </td>
        <td><%= link_to 'Destroy', honors_and_award, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' } %>
          <span class="glyphicon glyphicon-remove"></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honors And Award', new_honors_and_award_path, class: "btn btn-default" %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body" id="myModalBody">
      </div>
    </div>
  </div>
</div>

app/views/honors_and_awards/new.html.erb
<h1>New Honors And Award</h1>

<%= render 'form', honors_and_award: @honors_and_award %>

<%= link_to 'Back', honors_and_awards_path %>

app/views/honors_and_awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @honors_and_award.owner %>
</p>

<p>
  <strong>Honor date:</strong>
  <%= @honors_and_award.honor_date %>
</p>

<p>
  <strong>Honor name:</strong>
  <%= @honors_and_award.honor_name %>
</p>

<p>
  <strong>Honor description:</strong>
  <%= @honors_and_award.honor_description %>
</p>

<%= link_to 'Edit', edit_honors_and_award_path(@honors_and_award) %> |
<%= link_to 'Back', dashboard_index_path %>